# This is just used so you can test out the final changes before this gets merged and published

FROM nginx:alpine AS runtime
COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./dist/client /usr/share/nginx/html
EXPOSE 8080