// Autogenerated: Astro "env.d.ts" TypeScript Declaration File
//
// ▶ WARN: DO NOT CHANGE OR DELETE THIS FILE MANUALLY!
// - This file is automatically generated for you by Astro.
// - It is safe to check into version control (git, etc.)
// - Any changes to this file WILL be automatically overwritten.
//
// To define your own custom type declarations, create a new 
// "*.d.ts" file in your project directory (ex: "src/types.d.ts").

/// <reference path="../.astro/types.d.ts" />
/// <reference types="astro/client" />
