packages:
  - 'packages/**/*'
  - 'packages/astro/test/units/_temp-fixtures'
  - 'examples/**/*'
  - 'triage/*'
  - 'smoke/**/*'
  - 'temp/*'
  - 'scripts'
  - 'benchmark'
  - 'benchmark/packages/*'
  - 'benchmark/static-projects/*'
  # Below excludes are only for Turbo because it doesn't respect gitignore like pnpm does
  - '!packages/astro/test/units/_temp-fixtures/*'
  - '!**/.vercel/**'

# Important! Never install `astro` even when new version is in registry
preferWorkspacePackages: true
linkWorkspacePackages: true
saveWorkspaceProtocol: false # This prevents the examples to have the `workspace:` prefix
autoInstallPeers: false

overrides:
  # See https://github.com/withastro/astro/pull/16448
  'picomatch@<4': '^2.3.2'
  'vite@^7': '^7.3.2'

publicHoistPattern:
  # `astro sync` could try to import `@astrojs/db` but could fail due to linked dependencies in the monorepo.
  # We hoist it here so that it can easily resolve `@astrojs/db` without hardcoded handling.
  - '@astrojs/db'
# Wait until three days after release to install new versions of packages
minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  # TODO: remove once more stable
  - '@flue/*'
  - '@astrojs/*'
  # Netlify Vite Plugin and deps. New version required for bug fix.
  # TODO: remove this block after 2026/05/15
  - '@netlify/vite-plugin@2.12.3'
  - '@netlify/dev@4.18.3'
  - '@netlify/runtime@4.1.21'
  - '@netlify/edge-functions-dev@1.0.17'
  - '@netlify/blobs@10.7.5'
  - '@netlify/functions-dev@1.2.8'
  - '@netlify/otel@6.0.0'
  - '@netlify/zip-it-and-ship-it@14.5.6'
peerDependencyRules:
  allowAny:
    - 'astro'
    - 'vite'
onlyBuiltDependencies:
  - 'esbuild'
  - 'workerd'
  - '@biomejs/biome'
  - 'sharp'
  - '@parcel/watcher'
  - 'keytar'
  - '@vscode/vsce-sign'

patchedDependencies:
  '@changesets/get-github-info@0.7.0': patches/@changesets__get-github-info@0.7.0.patch

# Prevent installation of packages where trust level decreases
trustPolicy: 'no-downgrade'
trustPolicyExclude:
  # Netlify dependency they need to update: https://github.com/netlify/primitives/pull/585
  - 'chokidar@4.0.3'
  # Netlify packages that do not have trusted publishing enabled on npm
  # TODO: Remove once trusted publishing is enabled. Netlify are working on it.
  - '@netlify/edge-bundler@14.10.1'
  - '@netlify/zip-it-and-ship-it@14.5.6'
  - '@netlify/serverless-functions-api@2.15.1'
  # Outdated dependencies of @vitejs/plugin-react@^5 and @vscode/vsce
  # TODO: Update the Vite plugin to ^6 in Astro v7 and remove this
  - 'semver@6.3.1 || 5.7.2'
  # Old dependency of @types/node@22
  # TODO: Remove when dropping support for Node 22
  - undici-types@6.21.0
  # Dependencies in the docs repo that gets cloned for smoke tests
  - 'undici@5.29.0'
  - 'algoliasearch@4.27.0'
  - '@algolia/client-analytics@4.27.0'
  - '@algolia/recommend@4.27.0'
  - '@algolia/client-search@4.27.0'
  - '@algolia/requester-browser-xhr@4.27.0'
  - '@algolia/requester-node-http@4.27.0'
  - '@algolia/client-common@4.27.0'
  - '@algolia/logger-console@4.27.0'
  - '@algolia/client-personalization@4.27.0'

# Control whether packages can run postinstall scripts. We disallow this to avoid the security risk
# of running third-party code on install.
allowBuilds:
  '@google/genai': false
  '@mongodb-js/zstd': false
  '@parcel/watcher': false
  '@vscode/vsce-sign': false
  esbuild: false
  keytar: false
  node-liblzma: false
  protobufjs: false
  sharp: false
  workerd: false
