packages:
  - packages/**/*
  - packages/astro/test/units/_temp-fixtures
  - examples/**/*
  - triage/*
  - smoke/**/*
  - scripts
  - benchmark
  - benchmark/packages/*
  - benchmark/static-projects/*
  - '!packages/astro/test/units/_temp-fixtures/*'
  - '!**/.vercel/**'

autoInstallPeers: false

linkWorkspacePackages: true

minimumReleaseAgeExclude:
  - '@cloudflare/*'
  - wrangler

onlyBuiltDependencies:
  - esbuild
  - workerd
  - '@biomejs/biome'
  - sharp
  - '@parcel/watcher'
  - keytar
  - '@vscode/vsce-sign'

overrides:
  '@astrojs/node': link:packages/integrations/node
  astro: link:packages/astro

peerDependencyRules:
  allowAny:
    - astro
    - vite

preferWorkspacePackages: true

publicHoistPattern:
  - '@webcomponents/template-shadowroot'
  - '*lit*'
  - '@astrojs/db'

saveWorkspaceProtocol: false
