packages:
  - 'packages/**/*'
  - 'packages/astro/test/units/_temp-fixtures'
  - 'examples/**/*'
  - 'smoke/**/*'
  - 'scripts'
  - 'benchmark'
  - 'benchmark/packages/*'
  # Below excludes are only for Turbo because it doesn't respect gitignore like pnpm does
  - '!packages/astro/test/units/_temp-fixtures/*'
  - '!**/.vercel/**'

# Wait until three days after release to install new versions of packages
# TODO: uncomment before merging into main
# minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - '@biomejs/*'
  - '@cloudflare/*'
  - 'wrangler'
