packages:
  - 'packages/**/*'
  - 'packages/astro/test/units/_temp-fixtures'
  - 'examples/**/*'
  - 'smoke/**/*'
  - 'scripts'
  - 'benchmark'
  - 'benchmark/packages/*'
  # Below excludes are only for Turbo because it doesn't respect gitignore like pnpm does
  - '!packages/astro/test/units/_temp-fixtures/*'
  - '!**/.vercel/**'
# TODO: remove in Astro 6
overrides:
  # A later wrangler minor dropeed support for node 18
  'wrangler': '4.14.1'
  # TODO: fix upstream
  # 0.30.2 scans too many files
  '@vercel/nft': '0.30.1'
# Wait until three days after release to install new versions of packages
# TODO: uncomment before merging into main
# minimumReleaseAge: 4320
