packages:
  - 'packages/**/*'
  - 'packages/astro/test/units/_temp-fixtures'
  - 'examples/**/*'
  - 'smoke/**/*'
  - 'scripts'
  - 'benchmark'
  - 'benchmark/packages/*'
  - 'benchmark/static-projects/*'
  # Below excludes are only for Turbo because it doesn't respect gitignore like pnpm does
  - '!packages/astro/test/units/_temp-fixtures/*'
  - '!**/.vercel/**'

# Important! Never install `astro` even when new version is in registry
preferWorkspacePackages: true
linkWorkspacePackages: true
saveWorkspaceProtocol: false # This prevents the examples to have the `workspace:` prefix
autoInstallPeers: false

# Vite's esbuild optimizer has trouble optimizing `@astrojs/lit/client-shim.js`
# which imports this dependency.
publicHoistPattern:
  - '@webcomponents/template-shadowroot'
  # There's a lit dependency duplication somewhere causing multiple Lit versions error.
  - '*lit*'
  # `astro sync` could try to import `@astrojs/db` but could fail due to linked dependencies in the monorepo.
  # We hoist it here so that it can easily resolve `@astrojs/db` without hardcoded handling.
  - '@astrojs/db'
# TODO: remove in Astro 6
overrides:
  # Cheerio uses ^7, which requires node 20
  'undici': '^6.21.3'
  # A later wrangler minor dropeed support for node 18
  'wrangler': '4.14.1'
# Wait until three days after release to install new versions of packages
minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - '@biomejs/*'
  # TODO: remove in a few days
  - 'devalue'
  # Temporary, so we can install new lightweight updates
  - 'fontace'
  - '@capsizecss/unpack'
peerDependencyRules:
  allowAny:
    - 'astro'
    - 'vite'
onlyBuiltDependencies:
  - 'esbuild'
  - 'workerd'
  - '@biomejs/biome'
  - 'sharp'
  - '@parcel/watcher'
  - 'keytar'
  - '@vscode/vsce-sign'
# TODO: enable when viable
# trustPolicy: 'no-downgrade'
