[package]
name = "mdx-rs-parser"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2", default-features = false, features = ["napi8"] }
napi-derive = "2"
markdown = "1.0.0-alpha.21"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rmp-serde = "1"

[build-dependencies]
napi-build = "2"

[profile.release]
lto = true