/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function parseToAst(content: string): string
export declare function generateFromAst(astJson: string): string
export declare function compileMdx(content: string): string
export declare function parseToAstBinary(content: string): Buffer
export declare function generateFromAstBinary(astBinary: Buffer): string
