/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function parseToAst(content: string): string
export declare function generateFromAst(astJson: string): string
export declare function compileMdx(content: string): string
