/**
 * WE-FAST Built-in Templates & Block Definitions (`templates/index.ts`)
 * Combines Astro (hybrid island architecture), Nuxt/Vue composition widgets,
 * Svelte surgical reactive components, Bootstrap responsive grids, and GFX shader blocks!
 */

export interface WeFastComponentBlock {
  id: string;
  type: string;
  category: 'navigation' | 'hero' | 'features' | 'pricing' | 'gfx' | 'contact' | 'footer';
  framework: 'astro' | 'vue' | 'svelte' | 'bootstrap' | 'gfx';
  title: string;
  description: string;
  colSpan: 'col-12' | 'col-lg-6' | 'col-lg-4' | 'col-lg-8';
  padding: 'py-2' | 'py-3' | 'py-4' | 'py-5';
  islandHydration: 'client:load' | 'client:visible' | 'client:idle' | 'static';
  props: Record<string, any>;
  gfxOptions?: {
    shaderType: 'cyber-tunnel' | 'inline-raytracer' | 'neon-waves' | 'particle-mesh';
    speed: number;
    colorSpeed: number;
    density: number;
    bloom: number;
  };
}

export interface WeFastSiteTemplate {
  id: string;
  name: string;
  description: string;
  themeKey: 'cyberNeon' | 'indigoSaaS' | 'emeraldEco' | 'bistroWarm' | 'default';
  blocks: WeFastComponentBlock[];
}

export const WE_FAST_TEMPLATES: WeFastSiteTemplate[] = [
  {
    id: 'saas-ai',
    name: 'SaaS AI Platform (WE-FAST AI)',
    description: 'High-octane cyber-themed AI developer platform with GFX raymarched tunnel, Nuxt terminal demo, and Svelte interactive tabs.',
    themeKey: 'cyberNeon',
    blocks: [
      {
        id: 'nav-1',
        type: 'BootstrapNavbar',
        category: 'navigation',
        framework: 'bootstrap',
        title: 'Top Navigation Bar',
        description: 'Responsive Bootstrap header with logo and CTA.',
        colSpan: 'col-12',
        padding: 'py-2',
        islandHydration: 'static',
        props: {
          brandName: 'WE-FAST AI',
          brandBadge: 'v1.0',
          links: ['Features', 'DXR Shaders', 'Pricing', 'Documentation'],
          ctaText: 'Launch Studio',
        },
      },
      {
        id: 'hero-gfx-1',
        type: 'GfxCyberHero',
        category: 'hero',
        framework: 'gfx',
        title: 'GFX Raymarched Cyber-Tunnel Hero',
        description: 'Direct3D12/WebGL inspired interactive neon shader canvas background with live controls.',
        colSpan: 'col-12',
        padding: 'py-5',
        islandHydration: 'client:load',
        props: {
          heading: 'Build Websites at Quantum Velocity',
          subheading: 'Combining Astro Island Hydration, Nuxt/Vue Reactivity, Svelte 5 Surgical DOM, and GFX Shaders.',
          btnPrimaryText: 'Deploy Now',
          btnSecondaryText: 'Inspect Shaders',
        },
        gfxOptions: {
          shaderType: 'cyber-tunnel',
          speed: 1.2,
          colorSpeed: 1.5,
          density: 24,
          bloom: 0.9,
        },
      },
      {
        id: 'features-grid-1',
        type: 'NuxtFeatureGrid',
        category: 'features',
        framework: 'vue',
        title: 'Nuxt / Vue 3 Interactive Feature Showcase',
        description: 'Reactive 3-column Bootstrap cards powered by Vue Composition API.',
        colSpan: 'col-12',
        padding: 'py-5',
        islandHydration: 'client:visible',
        props: {
          sectionTitle: 'Architectural Superiority',
          cards: [
            { title: 'Astro Island Engine', desc: 'Zero-JS static defaults with selective component hydration (`client:load`).', icon: '🚀', badge: 'Fastest' },
            { title: 'Nuxt & Vue 3 Integration', desc: 'Auto-imports, reactive state stores, and seamless full-stack API capabilities.', icon: '💚', badge: 'Reactive' },
            { title: 'Svelte Surgical DOM', desc: 'Svelte compiler transforms components into pure JavaScript without virtual DOM.', icon: '🔥', badge: 'Surgical' },
          ],
        },
      },
      {
        id: 'pricing-svelte-1',
        type: 'SveltePricingTable',
        category: 'pricing',
        framework: 'svelte',
        title: 'Svelte Reactive Pricing Switcher',
        description: 'Svelte 5 component with smooth billing frequency toggle and tier cards.',
        colSpan: 'col-12',
        padding: 'py-5',
        islandHydration: 'client:visible',
        props: {
          sectionTitle: 'Transparent High-Octane Pricing',
          monthlyDiscount: 'Save 25% Annually',
          tiers: [
            { name: 'Starter', priceMonthly: '$19', priceYearly: '$14', desc: 'Ideal for indie hackers and prototypes.', features: ['3 Website Projects', 'Bootstrap 5 Grid', 'Standard GFX Shaders', 'Community Support'] },
            { name: 'Pro Studio', priceMonthly: '$49', priceYearly: '$36', desc: 'For agencies and power builders.', features: ['Unlimited Projects', 'Custom GFX Shader Reloading', 'Multi-Framework Export (Vue/Svelte/Astro)', 'Priority DXR Support'], highlight: true },
            { name: 'Enterprise Island', priceMonthly: '$199', priceYearly: '$149', desc: 'Custom island clusters and dedicated CDN.', features: ['Custom AST Plugins', 'White-label Studio', 'SSO & Role Management', '24/7 SLA Guarantee'] },
          ],
        },
      },
      {
        id: 'footer-1',
        type: 'AstroFooter',
        category: 'footer',
        framework: 'astro',
        title: 'Static Astro Hybrid Footer',
        description: 'Fast static footer with social links and copyright.',
        colSpan: 'col-12',
        padding: 'py-4',
        islandHydration: 'static',
        props: {
          companyName: 'WE-FAST Inc.',
          copyrightYear: '2026',
          tagline: 'Combining kariitsme/astro + nuxt + bootstrap + svelte + gfx into perfection.',
        },
      },
    ],
  },
  {
    id: 'ecommerce-nextgen',
    name: 'Modern E-Commerce Store (NextGen Goods)',
    description: 'Sleek responsive store with Bootstrap product grids, Svelte reactive shopping drawer, and GFX product glow.',
    themeKey: 'indigoSaaS',
    blocks: [
      {
        id: 'nav-ecom-1',
        type: 'BootstrapNavbar',
        category: 'navigation',
        framework: 'bootstrap',
        title: 'E-Commerce Store Header',
        description: 'Navbar with live shopping bag counter and categories.',
        colSpan: 'col-12',
        padding: 'py-2',
        islandHydration: 'static',
        props: {
          brandName: 'NextGen Goods',
          brandBadge: 'STORE',
          links: ['New Arrivals', '3D Techware', 'Cyber Accessories', 'Sale'],
          ctaText: 'Cart (3)',
        },
      },
      {
        id: 'hero-ecom-gfx',
        type: 'GfxCyberHero',
        category: 'hero',
        framework: 'gfx',
        title: 'Inline Raytraced Product Hologram Hero',
        description: 'DXR-1.1 inspired 3D sphere raymarching shader backdrop.',
        colSpan: 'col-12',
        padding: 'py-5',
        islandHydration: 'client:load',
        props: {
          heading: 'The Future of Tech Apparel is Here',
          subheading: 'Engineered for extreme performance and cybernetic aesthetics.',
          btnPrimaryText: 'Shop New Collection',
          btnSecondaryText: 'Explore 3D Fit',
        },
        gfxOptions: {
          shaderType: 'inline-raytracer',
          speed: 0.8,
          colorSpeed: 1.2,
          density: 16,
          bloom: 1.0,
        },
      },
      {
        id: 'products-grid-vue',
        type: 'NuxtFeatureGrid',
        category: 'features',
        framework: 'vue',
        title: 'Vue 3 Product Grid with Quick-Add',
        description: 'Reactive Bootstrap 12-column product catalog.',
        colSpan: 'col-12',
        padding: 'py-5',
        islandHydration: 'client:load',
        props: {
          sectionTitle: 'Featured Cyber Goods',
          cards: [
            { title: 'Quantum Visor X1', desc: 'Integrated HUD with real-time shader overlays and UV shielding.', icon: '👓', badge: '$249' },
            { title: 'Graphene Smart Jacket', desc: 'Adaptive thermal regulation with haptic feedback mesh.', icon: '🧥', badge: '$399' },
            { title: 'Neural Wristband v4', desc: 'Direct biometric sync and ultra-low latency gesture control.', icon: '⌚', badge: '$179' },
          ],
        },
      },
      {
        id: 'footer-ecom',
        type: 'AstroFooter',
        category: 'footer',
        framework: 'astro',
        title: 'E-Commerce Footer',
        description: 'Footer block with links and trust badges.',
        colSpan: 'col-12',
        padding: 'py-4',
        islandHydration: 'static',
        props: {
          companyName: 'NextGen Goods LLC',
          copyrightYear: '2026',
          tagline: 'Powered by WE-FAST Island Architecture.',
        },
      },
    ],
  },
  {
    id: 'agency-3d',
    name: 'Creative Agency & 3D Portfolio (Studio GFX)',
    description: 'Immersive agency showcase featuring interactive 3D particle network and Svelte animated client tabs.',
    themeKey: 'emeraldEco',
    blocks: [
      {
        id: 'nav-agency',
        type: 'BootstrapNavbar',
        category: 'navigation',
        framework: 'bootstrap',
        title: 'Agency Header',
        description: 'Clean minimalist navbar.',
        colSpan: 'col-12',
        padding: 'py-2',
        islandHydration: 'static',
        props: {
          brandName: 'Studio GFX',
          brandBadge: 'AGENCY',
          links: ['Work', 'Shaders', 'About Us', 'Careers'],
          ctaText: 'Start Project',
        },
      },
      {
        id: 'hero-agency-mesh',
        type: 'GfxCyberHero',
        category: 'hero',
        framework: 'gfx',
        title: '3D Interactive Particle Mesh Network Hero',
        description: 'GPU-simulated particle connections interacting with user parameters.',
        colSpan: 'col-12',
        padding: 'py-5',
        islandHydration: 'client:load',
        props: {
          heading: 'We Craft Digital Masterpieces',
          subheading: 'High-performance interactive experiences powered by WebGL & Direct3D principles.',
          btnPrimaryText: 'View Case Studies',
          btnSecondaryText: 'Our Technology',
        },
        gfxOptions: {
          shaderType: 'particle-mesh',
          speed: 1.0,
          colorSpeed: 2.0,
          density: 35,
          bloom: 0.85,
        },
      },
      {
        id: 'agency-stats-vue',
        type: 'NuxtFeatureGrid',
        category: 'features',
        framework: 'vue',
        title: 'Vue 3 Agency Impact Metrics',
        description: 'Stats grid with animated numbers.',
        colSpan: 'col-12',
        padding: 'py-4',
        islandHydration: 'client:visible',
        props: {
          sectionTitle: 'Our Track Record',
          cards: [
            { title: '300+ Modules', desc: 'Extensible Nuxt/Astro component integrations created.', icon: '📦', badge: 'Ecosystem' },
            { title: '99.99% FPS Stable', desc: 'Surgical Svelte DOM updates ensuring buttery smooth 60fps renders.', icon: '⚡', badge: 'Performance' },
            { title: '10x Prototyping Speed', desc: 'From initial concept to full multi-framework deployment in minutes.', icon: '🏎️', badge: 'Velocity' },
          ],
        },
      },
      {
        id: 'footer-agency',
        type: 'AstroFooter',
        category: 'footer',
        framework: 'astro',
        title: 'Agency Footer',
        description: 'Footer with contact info.',
        colSpan: 'col-12',
        padding: 'py-4',
        islandHydration: 'static',
        props: {
          companyName: 'Studio GFX & Co.',
          copyrightYear: '2026',
          tagline: 'Designing the next frontier of web graphics.',
        },
      },
    ],
  },
  {
    id: 'crypto-defi',
    name: 'Crypto & Web3 Landing (DeFi Pulse)',
    description: 'Neon liquid wave aesthetic with real-time yield calculators and interactive chart previews.',
    themeKey: 'cyberNeon',
    blocks: [
      {
        id: 'nav-defi',
        type: 'BootstrapNavbar',
        category: 'navigation',
        framework: 'bootstrap',
        title: 'DeFi Protocol Header',
        description: 'Navbar with wallet connect CTA.',
        colSpan: 'col-12',
        padding: 'py-2',
        islandHydration: 'static',
        props: {
          brandName: 'DeFi Pulse',
          brandBadge: 'WEB3',
          links: ['Ecosystem', 'Liquidity', 'Governance', 'Whitepaper'],
          ctaText: 'Connect Wallet',
        },
      },
      {
        id: 'hero-defi-waves',
        type: 'GfxCyberHero',
        category: 'hero',
        framework: 'gfx',
        title: 'Neon Liquid Waves Hero',
        description: 'Sinuous procedural neon waves running at 60fps.',
        colSpan: 'col-12',
        padding: 'py-5',
        islandHydration: 'client:load',
        props: {
          heading: 'Decentralized Liquidity at Light-Speed',
          subheading: 'Earn up to 24.5% APY with automated risk-adjusted farming strategies.',
          btnPrimaryText: 'Launch DApp',
          btnSecondaryText: 'View Audit Report',
        },
        gfxOptions: {
          shaderType: 'neon-waves',
          speed: 1.5,
          colorSpeed: 1.8,
          density: 20,
          bloom: 1.0,
        },
      },
      {
        id: 'defi-pricing-svelte',
        type: 'SveltePricingTable',
        category: 'pricing',
        framework: 'svelte',
        title: 'Svelte Staking Tiers',
        description: 'Staking pool selection and APY estimation.',
        colSpan: 'col-12',
        padding: 'py-5',
        islandHydration: 'client:visible',
        props: {
          sectionTitle: 'Select Your Staking Tier',
          monthlyDiscount: 'Boost APY +10%',
          tiers: [
            { name: 'Core Liquidity', priceMonthly: '8.2% APY', priceYearly: '12.5% APY', desc: 'No lockup period, instant withdrawals.', features: ['USDC/ETH Pool', 'Auto-compounding rewards', 'Gas-free claims', 'Zero deposit fees'] },
            { name: 'Quantum Vault', priceMonthly: '18.4% APY', priceYearly: '24.5% APY', desc: '30-day smart contract lockup.', features: ['Multi-chain yield farming', 'Governance voting multiplier', 'Priority liquidation protection', 'Free NFT booster'], highlight: true },
            { name: 'Institutional', priceMonthly: 'Custom APY', priceYearly: 'Max Yield', desc: 'For treasuries & whales > $1M.', features: ['Dedicated yield strategist', 'Custom risk profile parameters', 'Private RPC node access', 'On-chain insurance coverage'] },
          ],
        },
      },
      {
        id: 'footer-defi',
        type: 'AstroFooter',
        category: 'footer',
        framework: 'astro',
        title: 'DeFi Footer',
        description: 'Footer with compliance and security badges.',
        colSpan: 'col-12',
        padding: 'py-4',
        islandHydration: 'static',
        props: {
          companyName: 'DeFi Pulse Protocol Foundation',
          copyrightYear: '2026',
          tagline: 'Audited by Top Security Partners.',
        },
      },
    ],
  },
  {
    id: 'docs-portal',
    name: 'Developer Documentation Portal (NuxtAstro Docs)',
    description: 'Clean typography, code snippets, and fast Astro markdown hybrid rendering.',
    themeKey: 'default',
    blocks: [
      {
        id: 'nav-docs',
        type: 'BootstrapNavbar',
        category: 'navigation',
        framework: 'bootstrap',
        title: 'Docs Header',
        description: 'Navbar with quick search trigger.',
        colSpan: 'col-12',
        padding: 'py-2',
        islandHydration: 'static',
        props: {
          brandName: 'NuxtAstro Docs',
          brandBadge: 'GUIDES',
          links: ['Getting Started', 'Components', 'API Reference', 'GitHub'],
          ctaText: 'Search Docs (Ctrl+K)',
        },
      },
      {
        id: 'hero-docs-clean',
        type: 'GfxCyberHero',
        category: 'hero',
        framework: 'gfx',
        title: 'Clean Cyber-Grid Header',
        description: 'Minimalist grid animation for technical documentation.',
        colSpan: 'col-12',
        padding: 'py-4',
        islandHydration: 'client:load',
        props: {
          heading: 'Documentation for WE-FAST Multi-Framework Engine',
          subheading: 'Learn how to build hybrid applications combining Vue, Svelte, Bootstrap, and GFX inside Astro.',
          btnPrimaryText: 'Quick Start Guide',
          btnSecondaryText: 'Architecture Specs',
        },
        gfxOptions: {
          shaderType: 'cyber-tunnel',
          speed: 0.6,
          colorSpeed: 0.8,
          density: 15,
          bloom: 0.5,
        },
      },
      {
        id: 'docs-features-vue',
        type: 'NuxtFeatureGrid',
        category: 'features',
        framework: 'vue',
        title: 'Quick Links & Chapters',
        description: 'Chapter grid with code preview icons.',
        colSpan: 'col-12',
        padding: 'py-5',
        islandHydration: 'client:visible',
        props: {
          sectionTitle: 'Core Concepts',
          cards: [
            { title: '1. Island Hydration (`client:*`)', desc: 'How Astro isolates interactive islands while keeping 95% of your page pure zero-JS static HTML.', icon: '🏝️', badge: 'Core' },
            { title: '2. Bootstrap Grid & Tokens', desc: 'Using `--bs-primary` and responsive 12-column layouts across all framework components.', icon: '📐', badge: 'Design' },
            { title: '3. GFX Shader Reflection', desc: 'Writing HLSL/WebGL shaders and dynamically reloading them at runtime with `gfxKernelReloadAll()`.', icon: '🎨', badge: 'Graphics' },
          ],
        },
      },
      {
        id: 'footer-docs',
        type: 'AstroFooter',
        category: 'footer',
        framework: 'astro',
        title: 'Docs Footer',
        description: 'Footer with repository links.',
        colSpan: 'col-12',
        padding: 'py-4',
        islandHydration: 'static',
        props: {
          companyName: 'NuxtAstro Documentation Group',
          copyrightYear: '2026',
          tagline: 'Open Source under MIT License.',
        },
      },
    ],
  },
  {
    id: 'bistro-warm',
    name: 'Restaurant & Hospitality (Bistro 5)',
    description: 'Warm inviting Bootstrap design with reactive Svelte table reservation menu filter.',
    themeKey: 'bistroWarm',
    blocks: [
      {
        id: 'nav-bistro',
        type: 'BootstrapNavbar',
        category: 'navigation',
        framework: 'bootstrap',
        title: 'Bistro Navbar',
        description: 'Inviting restaurant header.',
        colSpan: 'col-12',
        padding: 'py-2',
        islandHydration: 'static',
        props: {
          brandName: 'Bistro 5',
          brandBadge: 'DINING',
          links: ['Our Menu', 'Chef Special', 'Wine List', 'Location'],
          ctaText: 'Reserve Table',
        },
      },
      {
        id: 'hero-bistro-waves',
        type: 'GfxCyberHero',
        category: 'hero',
        framework: 'gfx',
        title: 'Warm Ambient Glow Hero',
        description: 'Gentle golden liquid waves setting a cozy dining atmosphere.',
        colSpan: 'col-12',
        padding: 'py-5',
        islandHydration: 'client:load',
        props: {
          heading: 'Culinary Artistry Meets Modern Elegance',
          subheading: 'Experience locally sourced organic ingredients prepared by Michelin-starred culinary engineers.',
          btnPrimaryText: 'Book Your Experience',
          btnSecondaryText: 'Explore Seasonal Menu',
        },
        gfxOptions: {
          shaderType: 'neon-waves',
          speed: 0.7,
          colorSpeed: 0.9,
          density: 14,
          bloom: 0.7,
        },
      },
      {
        id: 'bistro-menu-vue',
        type: 'NuxtFeatureGrid',
        category: 'features',
        framework: 'vue',
        title: 'Featured Culinary Creations',
        description: '3-col Bootstrap cards highlighting signature dishes.',
        colSpan: 'col-12',
        padding: 'py-5',
        islandHydration: 'client:visible',
        props: {
          sectionTitle: 'Chef Signature Selection',
          cards: [
            { title: 'Truffle Glazed Wagyu Ribeye', desc: 'A5 Miyazaki Wagyu served with wild mushrooms and aged balsamico reduction.', icon: '🥩', badge: '$85' },
            { title: 'Pan-Seared Chilean Sea Bass', desc: 'Over saffron risotto with crispy leeks and lemon thyme emulsion.', icon: '🐟', badge: '$48' },
            { title: 'Valrhona Chocolate Sphere', desc: 'Warm salted caramel pour over hazelnut praline and gold leaf.', icon: '🍫', badge: '$22' },
          ],
        },
      },
      {
        id: 'footer-bistro',
        type: 'AstroFooter',
        category: 'footer',
        framework: 'astro',
        title: 'Bistro Footer',
        description: 'Footer with opening hours and address.',
        colSpan: 'col-12',
        padding: 'py-4',
        islandHydration: 'static',
        props: {
          companyName: 'Bistro 5 Hospitality Group',
          copyrightYear: '2026',
          tagline: 'Open Tuesday — Sunday from 5:00 PM to 11:00 PM.',
        },
      },
    ],
  },
];
