import * as assert from 'node:assert/strict';
import { describe, it } from 'node:test';
import * as cheerio from 'cheerio';
import { loadFixture } from './test-utils.ts';

// `imageService: { build: 'cloudflare-binding' }` opts in to transforming static images
// with the IMAGES binding inside workerd during the build. Each optimized image is
// streamed out of the prerender worker on its own request, so nothing here depends on
// the whole image set fitting in memory.
//
// Both the binding and the Node-side fallback emit a valid WEBP, so the generated bytes
// alone cannot tell them apart. The adapter warns whenever it falls back, so this test
// raises the log level (fixtures build silently by default), captures stdout, and treats
// that warning as proof the streaming endpoint did not do its job.
describe('BindingBuildImageService build-time image generation', () => {
	const FALLBACK_WARNING = 'Falling back to the local image service';

	async function buildFixture(outDirName: string) {
		const fixture = await loadFixture({
			root: './fixtures/compile-custom-image-service/',
			outDir: `./dist/binding-build-image-service-${outDirName}/`,
		});
		const resetConfig = await fixture.editFile(
			'astro.config.mjs',
			(contents) =>
				contents.replace(
					"imageService: 'compile'",
					"imageService: { build: 'cloudflare-binding', runtime: 'cloudflare-binding' }",
				),
			false,
		);

		// Astro's node logger resolves `process.stdout` per write, so patching it here
		// intercepts the adapter's warnings.
		const log: string[] = [];
		const originalWrite = process.stdout.write.bind(process.stdout);
		process.stdout.write = ((chunk: any, ...rest: any[]) => {
			log.push(typeof chunk === 'string' ? chunk : Buffer.from(chunk).toString('utf8'));
			return (originalWrite as any)(chunk, ...rest);
		}) as typeof process.stdout.write;

		try {
			await fixture.build({ logLevel: 'warn' });
			return { fixture, html: await fixture.readFile('client/index.html'), log: log.join('') };
		} finally {
			process.stdout.write = originalWrite;
			resetConfig();
		}
	}

	it('streams IMAGES-binding output into the client directory instead of falling back', async () => {
		const { fixture, html, log } = await buildFixture('binding');

		// The binding handled every transform: nothing fell through to the Node side.
		assert.ok(
			!log.includes(FALLBACK_WARNING),
			`expected the IMAGES binding to transform every image, but the build fell back:\n${log}`,
		);

		const src = cheerio.load(html)('img').attr('src');
		assert.match(src ?? '', /^\/_astro\/.+\.webp$/, 'expected a hashed .webp asset in the markup');

		// The streamed bytes landed on disk as an intact WEBP container.
		const data = (await fixture.readFile(`client${src}`, null)) as unknown as Buffer;
		assert.equal(data.subarray(0, 4).toString('utf8'), 'RIFF');
		assert.equal(data.subarray(8, 12).toString('utf8'), 'WEBP');
	});
});
