name: "\U0001F41B Bug Report"
description: Report an issue or possible bug
title: "\U0001F41B "
labels: []
assignees: []
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to file a bug report! Please fill out this form as completely as possible.
  - type: checkboxes
    attributes:
      label: Environment Checklist
      options:
        - label: I am using the **latest version of Astro** and all plugins.
          required: true
        - label: I am using a version of Node that supports ESM (`v12.20.0+`, `v14.13.1+`, or `v16.0.0+`)
          required: true
  - type: dropdown
    attributes:
      label: What package manager are you using?
      options:
        - "`npm v6`"
        - "`npm v7`"
        - "`yarn v1 (classic)`"
        - "`yarn v2 (berry)`"
        - "`pnpm`"
        - "other (please mention in description)"
    validations:
      required: true
  - type: input
    attributes:
      label: What operating system are you using?
      description: 'For example: macOS, Windows, Linux'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: input
    attributes:
      label: Link to Minimal Reproducible Example
      description: "We can't fix bugs that we can't see for ourselves! Issues with clear, minimal reproducible examples are more likely to be fixed quickly."
      placeholder: 'https://github.com/username/repo'
  - type: textarea
    attributes:
      label: Steps to reproduce
      render: bash
      value: |
        # Setup
        git clone git@github.com:username/repo.git
        # OR npm init astro --template <name>
        
        # Steps to reproduce
        npm install
        npm run build 

        # Paste error below (or describe the issue)
        Error: ...
    validations:
      required: true
