name: "\U0001F4A1 Feature Request (Beta)"
about: 'Submit an RFC or suggest an idea for this project'
title: '[Feature Request] '
labels: []
assignees: []
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to suggest a new feature! Please fill out this form as completely as possible.
  - type: textarea
    attributes:
      label: Motivation
      description: |
        A quick, clear and concise description of what the problem is. 

        **Please include links to relevant issues, Discord convos, and anything else.**
      required: true
      placeholder: I want to be able to...
  - type: textarea
    attributes:
      label: Proposed Solution
      description: Your take on one (or more) possible solution(s) to problem.
      required: true
      value: |
        ### Possible solutions

        ### Alternatives considered

        ### Risks, downsides, and/or tradeoffs
  - type: textarea
    attributes:
      label: Detailed Design
      description: |
        🛑 **Just looking for feedback on an idea? Leave this section blank.**

        Otherwise, explain the exact steps required to implement this change.
        Include specific details that would help someone implement this feature.
  - type: textarea
    attributes:
      label: Open Questions
      description: |
        Are there any open questions remaining? List them here.
  - type: checkboxes
    attributes:
      label: Help make it happen!
      description: Tip: Requests made by interested contributors are much more likely to get done!
      required: true
      options:
        - label: I am willing to submit a PR to implement this change.
        - label: I am willing to submit a PR to implement this change, but would need some guidance.
        - label: I am not willing to submit a PR to implement this change.
