/* eslint-disable */
// @ts-nocheck
// TODO: don't precompile this, but it works for now
/* App.svelte generated by Svelte v3.37.0 */
import { create_ssr_component, validate_component } from 'svelte/internal';

const App = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  const { __astro_component: Component, __astro_children, ...props } = $$props;
  return `${validate_component(Component, 'Component').$$render($$result, Object.assign(props), {}, { default: () => `${__astro_children}` })}`;
});

export default App;
