import type { FlueContext } from '@flue/sdk/client';
import { defineCommand } from '@flue/sdk/node';
import * as v from 'valibot';
import {
	GITHUB_TOKEN_BASE,
	addPullRequestLabels,
	createPullRequest,
	fetchIssueDetails,
	postGitHubComment,
	removeGitHubLabel,
} from '../lib/github.ts';

// CLI-only agent: no HTTP trigger. Invoked from GitHub Actions via `flue run fix-verification`.
export const triggers = {};

const gh = defineCommand('gh', { env: { GH_TOKEN: GITHUB_TOKEN_BASE } });
const git = defineCommand('git');
const node = defineCommand('node');
const pnpm = defineCommand('pnpm');

export default async function ({ init, payload }: FlueContext) {
	const issueNumber = payload.issueNumber as number;
	const branch = `flue/fix-${issueNumber}`;

	const agent = await init({
		sandbox: 'local',
		model: 'anthropic/claude-sonnet-4-20250514',
	});
	const session = await agent.session();

	const issueDetails = await fetchIssueDetails(issueNumber);

	// Find the latest non-bot comment — this is the one that triggered the workflow.
	const latestUserComment = [...issueDetails.comments]
		.reverse()
		.find((c) => c.author.login !== 'astrobot-houston' && c.author.login !== 'github-actions[bot]');

	if (!latestUserComment) {
		console.info('No user comment found, skipping verification.');
		return { verified: false, reason: 'no user comment' };
	}

	// Ask the LLM whether this comment confirms the fix works.
	const classification = await session.prompt(
		`You are reviewing a GitHub issue comment to determine if the commenter is confirming that a proposed fix works.

## Context

An automated triage bot found a fix for issue #${issueNumber} and published a preview release for the reporter to test. The bot asked the reporter to install the preview and confirm whether the fix resolves their issue.

## Issue
**${issueDetails.title}**

${issueDetails.body}

## Recent conversation
${issueDetails.comments
	.slice(-10)
	.map((c) => `**@${c.author.login}** (${c.authorAssociation}):\n${c.body}`)
	.join('\n\n---\n\n')}

## Comment to classify
**@${latestUserComment.author.login}** (${latestUserComment.authorAssociation}):
${latestUserComment.body}

## Your Task

Determine if this comment is a **positive confirmation** that the fix works. Examples of positive confirmation:
- "It works!"
- "Confirmed, this fixes my issue"
- "Tested the preview release, the bug is gone"
- "Thanks, that solved it"
- Thumbs up or similar positive reaction with clear reference to testing

Examples of comments that are NOT positive confirmation:
- Asking questions ("How do I install this?")
- Reporting the fix doesn't work ("Still broken", "Same error")
- Unrelated discussion
- Acknowledgment without testing ("Thanks, I'll try it later")
- The bot's own messages

Return your classification.`,
		{
			result: v.object({
				verified: v.pipe(
					v.boolean(),
					v.description('true if the comment positively confirms the fix works'),
				),
				reasoning: v.pipe(
					v.string(),
					v.description('Brief explanation of why you classified this way'),
				),
			}),
		},
	);

	console.info('Verification classification:', classification);

	if (!classification.verified) {
		return { verified: false, reason: classification.reasoning };
	}

	// The fix is verified! Remove the label and create a PR.
	await removeGitHubLabel(issueNumber, 'fix pending verification');

	// Use the astro-pr-writer skill to generate a good PR title and body.
	const prContent = await session.skill('astro-pr-writer/SKILL.md', {
		args: {
			issueNumber,
			issueDetails,
			branch,
			context: `This PR was auto-generated by the triage bot after the reporter confirmed the fix works.
The fix branch is "${branch}" targeting "main".
The issue reporter (@${latestUserComment.author.login}) confirmed the fix resolves their issue.
Generate a PR title and body following the astro-pr-writer conventions.
The PR should reference the issue with "Closes #${issueNumber}".
Do NOT create the PR yourself — just return the title and body content.`,
		},
		commands: [gh, git, node, pnpm],
		result: v.object({
			title: v.pipe(
				v.string(),
				v.description('The PR title, reviewer-friendly, no commit-style prefixes'),
			),
			body: v.pipe(v.string(), v.description('The full PR body in markdown')),
		}),
	});

	const pr = await createPullRequest({
		head: branch,
		base: 'main',
		title: prContent.title,
		body: prContent.body,
	});

	console.info(`PR created: ${pr.html_url}`);

	await addPullRequestLabels(pr.number, ['fix verified']);

	// Post a comment on the issue linking to the PR.
	await postGitHubComment(
		issueNumber,
		`The fix has been verified! A pull request has been created: ${pr.html_url}`,
	);

	return { verified: true, prNumber: pr.number, prUrl: pr.html_url };
}
