import { existsSync } from 'node:fs';
import { mkdir, writeFile } from 'node:fs/promises';
import type { DBTable, DBTables } from '../types.js';
import { DB_TYPES_FILE, RUNTIME_DRIZZLE_IMPORT, RUNTIME_IMPORT } from '../consts.js';

export async function typegen({ tables, root }: { tables: DBTables; root: URL }) {
	const content = `// This file is generated by \`studio sync\`
declare module 'astro:db' {
	export const db: import(${RUNTIME_IMPORT}).SqliteDB;
	export const dbUrl: string;
	export * from ${RUNTIME_DRIZZLE_IMPORT};

${Object.entries(tables)
	.map(([name, collection]) => generateTableType(name, collection))
	.join('\n')}
}
`;

	const dotAstroDir = new URL('.astro/', root);

	if (!existsSync(dotAstroDir)) {
		await mkdir(dotAstroDir);
	}

	await writeFile(new URL(DB_TYPES_FILE, dotAstroDir), content);
}

function generateTableType(name: string, collection: DBTable): string {
	let tableType = `	export const ${name}: import(${RUNTIME_IMPORT}).Table<
		${JSON.stringify(name)},
		${JSON.stringify(
			Object.fromEntries(
				Object.entries(collection.columns).map(([columnName, column]) => [
					columnName,
					{
						// Only select columns Drizzle needs for inference
						type: column.type,
						optional: column.schema.optional,
						default: column.schema.default,
					},
				])
			)
		)}
	>;`;
	return tableType;
}
