name: CI

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - '.vscode/**'
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [20.9.0, 22]
        include:
          - os: windows-latest
            node_version: 20.9.0
          - os: macos-latest
            node_version: 20.9.0
      fail-fast: false

    name: 'Test: node-${{ matrix.node_version }}, ${{ matrix.os }}'
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Setup PNPM
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

      - name: Setup node@${{ matrix.NODE_VERSION }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ matrix.NODE_VERSION }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build the packages
        run: pnpm build

      - name: Test (Linux)
        if: runner.os == 'Linux'
        run: |
          pnpm run test:skip-vs
          cd packages/vscode
          xvfb-run -a pnpm test
          cd ../ts-plugin
          xvfb-run -a pnpm test

      - name: Test
        run: pnpm test
        if: runner.os != 'Linux'
