name: Scripts

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"
    paths:
      - "packages/astro/src/runtime/client/**/*"
      - "!packages/astro/src/runtime/client/dev-toolbar/**/*"

permissions: {}

# Automatically cancel in-progress actions on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  bundle:
    name: Bundle Size
    runs-on: ubuntu-latest
    permissions:
      contents: read # Checkout only
      pull-requests: write # Post bundle size comparison comment
    steps:
      - name: Checkout Repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Checkout Main into tmp
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: main
          path: main

      - name: Setup PNPM
        uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6.0.8

      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24.15.0
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Check Bundle Size
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            const { default: script } = await import('${{ github.workspace }}/.github/scripts/bundle-size.mjs')
            await script({ github, context })
