name: Semgrep OSS scan

permissions: {}

on:
  pull_request: {}
  schedule:
    - cron: '0 0 * * 6'
jobs:
  semgrep:
    name: semgrep-oss
    runs-on: ubuntu-latest
    permissions:
      contents: read # Checkout only
    container:
      image: semgrep/semgrep@sha256:40579a2e70910d891959a4868711ba0399293949a2f1f141ddb5002d5fc7dd0f # v1.157.0
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - run: semgrep scan --config=auto
