import assert from 'node:assert/strict';
import { before, describe, it } from 'node:test';
import { loadFixture } from './test-utils.js';

describe('Assets generated by integrations', () => {
	/** @type {import('./test-utils.js').Fixture} */
	let fixture;

	before(async () => {
		fixture = await loadFixture({
			root: './fixtures/integration-assets/',
		});
		await fixture.build();
	});

	it('moves static assets generated by integrations to the correct location', async () => {
		const sitemap = await fixture.readFile('../.vercel/output/static/sitemap-index.xml');
		assert(sitemap.includes('<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'));
	});
});
