declare module 'node:*'
declare module '@ungap/structured-clone/esm/index.js'
declare module '@ungap/structured-clone/esm/deserialize.js'
declare module '@ungap/structured-clone/esm/serialize.js'
declare module 'abort-controller/dist/abort-controller.mjs'
declare module 'node-fetch/src/index.js'
declare module 'web-streams-polyfill/dist/ponyfill.es6.mjs'
